"""1

Revision ID: 2db2efc7393c
Revises: 
Create Date: 2024-01-11 10:02:08.459165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db2efc7393c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furnitures', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furnitures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
